// Generated by https://quicktype.io

class CovidNews {
  String status;
  int totalResults;
  List<Article> articles;

  CovidNews({
    this.status,
    this.totalResults,
    this.articles,
  });

  factory CovidNews.fromJson(Map<String, dynamic> json) {
    List arts = json['articles'] as List;
    List<Article> _articles = arts.map((art) => Article.fromJson(art)).toList();
    return CovidNews(
      status: json['status'],
      totalResults: json['totalResults'],
      articles: _articles
    );
  }
}

class Article {
  Source source;
  String author;
  String title;
  String description;
  String url;
  String urlToImage;
  String publishedAt;
  String content;

  Article({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });

  factory Article.fromJson(Map<String, dynamic> json) {
    return Article(
      source: Source.fromJson(json['source']),
      author: json['author'],
      title: json['title'],
      description: json['description'],
      url: json['url'],
      urlToImage: json['urlToImage'],
      publishedAt: json['publishedAt'],
      content: json['content']

    );
  }
}

class Source {
  String id;
  String name;

  Source({
    this.id,
    this.name,
  });

  factory Source.fromJson(Map<String, dynamic> json) {
    return Source(
      id: json['id'],
      name: json['name']
    );
  }
}
